### ISSUE TITLE
Quelques amélioration à faire pour la lisibilité

### ISSUE THREAD

**Issue by arsiak** [IFATech-Metz/dev-log-4#27]
- Projet fonctionnel 
- Le design peut être amélioré (On ne sait pas à quoi correspond les valeurs de la météo 5 jour, temp min, max ou moyenne ?
- Le menu burger n'est pas utilisable

**Comment by stephanieremy** [comment]
Merci arsiak, le design est en cours. 
Le menu burger va disparaitre au profit d'une barre fonctionnelle.

**Comment by Chaussettecin** [comment]
Reparer :) design plus que minimaliste mais bon
